server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: microservice
          uri: http://localhost:8081  # Your microservice route
          # uri: http://microservice-gowthamanprojects-dev.apps.rm2.thpm.p1.openshiftapps.com  # Your microservice route
          predicates:
            - Path=/v3/api-docs/microservice,/api/**
          filters:
            - AddAuthTokenHeader
            - RemoveRequestHeader=Authorization
      default-filters:
        - PreserveHostHeader
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://keycloak-gowthamanprojects-dev.apps.rm2.thpm.p1.openshiftapps.com/realms/myrealm/protocol/openid-connect/token/introspect
          client-id: gateway-client
          client-secret: IyDhXnUjTfe8A8FdDI78Mno0mm279g54

management:
  endpoints:
    web:
      exposure:
        include: health,info
swagger:
  ui: /swagger-ui.html
  config:
    refreshrate: 60000
springdoc:
  api-docs:
    path: /v3/api-docs
logging:
  level:
    com.poc.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG