---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: gowthamanprojects-dev
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway
  namespace: gowthamanprojects-dev
spec:
  to:
    kind: Service
    name: gateway
  port:
    targetPort: 8080
  wildcardPolicy: None